#ifndef BEETROOT_PLATFORM_DEFINES_H
#define BEETROOT_PLATFORM_DEFINES_H

#define BEET_TRUE 1
#define BEET_FALSE !BEET_TRUE

#define FEATURE_ON ==
#define FEATURE_OFF !=
#define CHECK_FEATURE(featureState) (BEET_TRUE featureState BEET_TRUE)

#if defined(_WIN32)
#define PLATFORM_WINDOWS FEATURE_ON
#define PLATFORM_LINUX FEATURE_OFF
#define PLATFORM_APPLE FEATURE_OFF
#elif defined(__linux__)
#define PLATFORM_WINDOWS FEATURE_OFF
#define PLATFORM_LINUX FEATURE_ON
#define PLATFORM_APPLE FEATURE_OFF
#elif defined(__APPLE__)
#define PLATFORM_APPLE FEATURE_OFF
#define PLATFORM_LINUX FEATURE_OFF
#define PLATFORM_WINDOWS FEATURE_ON
#endif

#define FEATURE_IN_DEV_RUNTIME_GLTF_LOADING FEATURE_ON

#endif //BEETROOT_PLATFORM_DEFINES_H